name: 'DotnetGithubLib'
description: 'Build, test, coverage, publish nuget.'

inputs:
  name:
    required: true
    description: 'Name of C# project.'
  owner:
    required: true
    description: 'Owner of the repo'
  owner-pat:
    required: true
    description: 'PAT for reading nuget packages in owner.'
  gh-token:
    required: true
    description: 'Github token for this repo for publishing nuger package.'
  codecov-key:
    description: 'Key for uploading codecov reports.'
    required: true
  dotnet-version:
    required: false
    default: 7.0.100-preview.3.22179.4
  config:
    required: false
    description: 'Release or debug other config name for MSBuild.'
    default: Release

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v4.0.2
      id: get-version
      with:
        bump_each_commit: true
        search_commit_body: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.3.22179.4

    - name: Athenticate
      run: dotnet nuget add source
        --username ${{ inputs.owner }}
        --password ${{ inputs.owner-pat }}
        --store-password-in-clear-text
        --name github "https://nuget.pkg.github.com/${{ inputs.owner }}/index.json"
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build
      run: dotnet build -c ${{ inputs.config }} --no-restore
      shell: bash

    - name: Test
      run: dotnet test
        -c ${{ inputs.config }}
        --no-build
        --collect:"XPlat Code Coverage"
        -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      shell: bash

    - name: ChangeDir
      run: cd ${{ inputs.name }}.Tests/TestResults && cd $(ls -d */|head -n 1)
      shell: bash

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ inputs.codecov-key }}
        file: coverage.opencover.xml

    - name: ChangeDir
      run: cd ../../..
      shell: bash

    - name: Package
      run: dotnet pack
        -c ${{ inputs.config }}
        --no-build
        -o out
        -p:PackageVersion=${{steps.get-version.outputs.version}}
      shell: bash

    - name: Athenticate For Push
      run: dotnet nuget update source github
        --username ${{ inputs.name }}
        --password ${{ inputs.gh-token }}
        --store-password-in-clear-text
      shell: bash

    - name: Publish
      run: dotnet nuget push
        --skip-duplicate
        "out/${{ inputs.name }}.${{steps.get-version.outputs.version}}.nupkg"
        -s github
      shell: bash
